### ISSUE TITLE
VSync issues

### ISSUE THREAD

**Issue by pierrep** [virtual-programming/bioshockinfinite-linux#11]
Original I thought this was due to my setup, but I'm not 100% sure now as I've tried it in both Ubuntu 14.04 and SteamOS and I'm getting tearing in both.

With the steam fps overlay on and Vsync turned on, I get  a flat 60fps.

Nvidia GTX660 and Haswell Refresh motherboard + i5

Should I not turn on Vsync on the nvidia-settings panel and only enable it in game (although this makes no difference)

**Comment by vpltd-peterm** [comment]
This seems to be a problem with desktop compositors on Linux in general. We ask GLX for vsync swap synchronisation and that is supposed to ensure that buffer swaps are synchronised. Ultimately though it is down to the compositor to handle it correctly.

I do not recommend forcing vsync on via the nvidia-settings panel.

**Comment by Wuerstchen** [comment]
For me it was said compositor problem. I had it in every game, even on the desktop when watching movies and stuff.
What I did was disabling my Compositor in Xfce settings and replace it with compton. No problems since then.
Nvidia GTX980 and Intel i5
