### ISSUE TITLE
Game crashes at random points

### ISSUE THREAD

**Issue by liamdawe** [virtual-programming/bioshockinfinite-linux#14]
Doing nothing out of the ordinary, was jumping from line to line with Elizabeth. Game just hard crashed.

Got two crash dmp files for you too: https://dl.dropboxusercontent.com/u/59913460/assert_20150426140208_22.dmp
https://dl.dropboxusercontent.com/u/59913460/crash_20150426134554_61.dmp

eON log: https://gist.githubusercontent.com/liamdawe/c6bd78164f1e47cab6b5/raw/gistfile1.txt

Edit: I realised hours later it left "E.runloop" process on my machine, and it was eating up 100% on all cores. That can't be good.

```
System info:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-15-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Metacity (Marco)
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 346.59
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                            47.7cm x 26.8cm  (54.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC887-VD
    
Memory:
    RAM:  15993 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  1877664 Mb
    Largest Free Hard Disk Block:  1495616 Mb
    
Installed software:
    
Recent Failure Reports:
    Sun Apr 26 13:02:11 2015 GMT: file ''/tmp/dumps/crash_20150426134554_61.dmp'', upload no: ''Failed sending data to the peer''
    Sun Apr 26 13:18:26 2015 GMT: file ''/tmp/dumps/assert_20150426140208_22.dmp'', upload no: ''Failed sending data to the peer''
    
```

**Comment by vpltd-peterm** [comment]
Ah we have seen this before during development, those dump files are actually made by the Steam API, and later on a deadlock occurs which stops the process exiting. 

We'll speak to Valve about this, as they assured us the problem was fixed...

**Comment by liamdawe** [comment]
Okay thanks, what about the crash itself buddy, any thoughts? Would like to give it a go, as apart from the crash (which is obviously off-putting) the performance is grand. Think this was on Ultra too with a mostly solid 60FPS.

**Comment by sysms** [comment]
@liamdawe: do you have a xbox360-controller connected to your system? if so, you may run into a UE/Kernel-Bug, which can be fixed by recompiling the xpad-module.

See http://steamcommunity.com/app/233130/discussions/0/611702631210587760/#c611702631218590990

For me it worked and fixed all hard crashes I had with various UE-Games.

**Comment by liamdawe** [comment]
No, I don't have any gamepad plugged in.

**Comment by vpltd-peterm** [comment]
The fact that it is Steam's copy of Breakpad firing suggests this is a problem with the Steam API somehow. We'll report it to Valve as they were aware of a similar problem before, and claimed it was fixed.

**Comment by liamdawe** [comment]
So, if I turn off Steam Overlay then you think it might not crash?

**Comment by vpltd-peterm** [comment]
No.. it's not related to the steam overlay, but the Steam API used by achievements and "Steam Cloud" storage

**Comment by liamdawe** [comment]
So, any news on this? I can seeminly crash it with alt+tab when using Compiz.

And every time E.runloop stays running killing my CPU using it all up.

**Comment by BT-Justice** [comment]
I have the same problem  After about 5-10 minutes of playing the game, it locks up.  I have to hit CTRL+ALT F2 then CTRL+ALT F7 so I can actually close the game.  I have Ubuntu MATE 14.04.2 LTS, 6-core AMD FX-6300 CPU, 12 GB RAM, and AMD Radeon HD 7770 using fglrx-updates restricted drivers.

**Comment by directhex** [comment]
@BT-Justice for shits & giggles, can you try either setting the launch options of the game to `taskset -c 0,3 %command%` OR run `echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor` in a terminal before starting the game?

**Comment by BT-Justice** [comment]
Those didn't make much of a difference.  As of late though if I start the game and it locks up, I open the MATE Task Manager and kill the Steam and Bioshock processes then relaunch the game and it plays for several hours with hardly any problems at all.

**Comment by BT-Justice** [comment]
I was able to beat the game a few minutes ago.  After the credits and music video, it froze :(

**Comment by christopherbeneke** [comment]
Has there been any resolution on this?  I am experiencing the same issue.  I did try the taskset trick but the game still crashes frequently.  The sound seems to stick, but I have to alt-tab and kill the process.

I'd like to disable the achievements because as indicated in the post from May 1st, it seems to be the culprit, but disabling the steam overlay does not disable the achievements.

If it makes any difference, I'm running:
Ubuntu 14.04 64 bit
Intel 5930K
GTX 980

**Comment by BT-Justice** [comment]
I am playing the game through again in 1999 mode to get the remaining accomplishments.  I notice about 90% of the time when the game locks up that there is a radio playing and ambient music on top of that.  Is this too much for PulseAudio to handle?

**Comment by CommanderAlchemy** [comment]
@BT-Justice You know that pulse does not process the actual game sound, it just moves it to the selected output resamples if needed etc. If its related to sound its something in the game's audioengine or eon wrapper.

**Comment by liamdawe** [comment]
I have not seen this bug for quite some time, probably since the crash bug was fixed for AMD which seems to have fixed it for me.
