### ISSUE TITLE
Game crashing at random points

### ISSUE THREAD

**Issue by mdornfe1** [virtual-programming/bioshockinfinite-linux#15]
I never really make it to playing the actual game. The game crashed once during the opening menu and another time during the opening cinematic. If I then try to quit Steam it says the Bioshock Infinite is still running. Here's the output from terminal for the second crash http://pastebin.com/vtDiSzYs. Here's the output of lshw http://pastebin.com/9dVdR2YB. Here's my graphics card info http://i.imgur.com/u6UcRGW.png. I'm running the game with primusrun. Here's the output of eon.txt http://pastebin.com/CL29jX5c and lspci http://pastebin.com/XUdF90dy.

**Comment by vpltd-peterm** [comment]
Related to #14

**Comment by vpltd-peterm** [comment]
Closing as duplicate of #14
