### ISSUE TITLE
inverted looked is the wrong way around for gamepads

### ISSUE THREAD

**Issue by liamdawe** [virtual-programming/bioshockinfinite-linux#16]
Not sure why, but with my Logitech F310, the inverted option default (off) is inverted.

**Comment by vpltd-peterm** [comment]
Is this definitely configured correctly in Steam Big Picture mode?

**Comment by liamdawe** [comment]
Yes, it's the same issue is Spec Ops, others have noted to me in GOL's comments (can't remember where) they also have the issue.

I've tested it extensively in other games, only happens in yours.

Spec Ops is even worse though, as i can't change the setting as it quickly flickers to on, and then off again.

**Comment by liamdawe** [comment]
This one explain the oddness of the scrolling: https://www.gamingonlinux.com/articles/spec-ops-the-line-released-for-linux-initial-port-report-included.5385/page=2#36982

" it keeps detecting input from the controller and scrolling through the menus, and the camera keeps turning"

That guy has a 360 controller, but It sounds like part of my issue.

Also this guy using DS4: https://www.gamingonlinux.com/articles/spec-ops-the-line-released-for-linux-initial-port-report-included.5385/page=3#37005

Same issue, inverted up/down.

**Comment by liamdawe** [comment]
Also this one: https://www.gamingonlinux.com/articles/spec-ops-the-line-released-for-linux-initial-port-report-included.5385/page=4#37010

"My only problem with SO, that I can't use my Logitech gamepad (same one which Liam has), because ingame it keeps spinning and in the menu it keeps scrolling endlessly."

**Comment by directhex** [comment]
Sounds like it's picking up one of the extra axises (axorum? axii?) from the triggers, which are an analog axis with a non-standard scale.

**Comment by liamdawe** [comment]
Any news on this?

**Comment by vpltd-peterm** [comment]
We'll be updating the game soon as we have some gamepad related fixes worked out (from Dirt Showdown). Just waiting for 2K's approval.

**Comment by liamdawe** [comment]
This is still an issue by the way.

**Comment by vpltd-peterm** [comment]
Do you know if the look is inverted on any other type of pad ? We can't see this being a problem in our code... so it's possible that the Logitech pad simply reports an inverted Y axis

**Comment by liamdawe** [comment]
I just tested it my DS4 controller and it's exactly the same issue, so it's not my controller. If it was, my Logitech would have the same issue in all games + the DS4 would be inverted when it reacts the same.

**Comment by ricki42** [comment]
I just tested Bioshock Infinite with both a DS4 and a Logitech F710. For both, I have to set inverted to 'on' for up to be up. I don't have Spec Ops installed at the moment, but I don't have this problem in other games.

**Comment by picueck** [comment]
I just tested Bioshock Infinite with a logitech F310.  initially the option that inverted axis y "off" the controller is off, i changed to "on" to work normally.

**Comment by liamdawe** [comment]
I see I am not alone then, so it is an issue and not on my end.

As I mentioned before, it's only an issue with your ports with gamepads having the mapping reversed for inverted look, everything else gamepad wise is fine in Bioshock.

Please look into it.

**Comment by vpltd-peterm** [comment]
It's odd because there's definitely nothing in our code that causes this.. so I did a little research, aka Googling....

It turns out, this is the behaviour under Windows as well, and it actually seems to be common to Unreal Engine 3 titles! For example:

http://www.gamefaqs.com/boards/955302-x-men-origins-wolverine/49391929
https://forums.epicgames.com/threads/583478-Gamepad-Issues-Movement-Inverted
http://steamcommunity.com/app/8870/discussions/0/864973760888413660/
http://forums.steampowered.com/forums/showthread.php?t=2482805

As this is original game behaviour, it is unlikely we will change it. Note that there are fixes that can be applied to the configuration for the game if you really find this annoying

**Comment by liamdawe** [comment]
Oeer, is it not possible to simply pop a quick check in for these titles in eON that use UE3?

**Comment by vpltd-peterm** [comment]
We probably could, but as the "invert Y axis" option in the games in question does what it's supposed to, it's not really worth us special casing this.

**Comment by liamdawe** [comment]
True enough I suppose, I will go ahead and close this since it's technically not your issue, and there is a toggle to make it work anyway so "meh".
