### ISSUE TITLE
No Sound At Any Point After Launching Bioshock Infinite

### ISSUE THREAD

**Issue by kartious** [virtual-programming/bioshockinfinite-linux#17]
When I launch Bioshock Infinite from the Splash Screens when the game is launching to creating a new game there is no sound output whatsoever, when I check Pulse Audio it picks up that the game is there but no matter what I do to the sound settings this does not seem to make a difference.

You can see a video example here where I play some music and launch another one of your games Borderlands 2 with sound being all well and good. After I launch Bioshock Infinite and there is no sound as described.

https://youtu.be/9R1AdTY6cb4

Here is a Gist page of the console output from launching Steam

https://gist.github.com/kartious/2dd1e65904ddc6e55da1

Here is another Gist of the contents of EON.txt and the contents of "/home/nick/.local/share/irrationalgames/bioshockinfinite/GameDocuments/My Games/BioShock Infinite/XGame/Config/"

https://gist.github.com/kartious/d7d16649de8b4e635d14

Here is the Output of lspci 

https://gist.github.com/kartious/16434dc70bf3fc8dee7b

Simple Specs:

Post your system information as follows:
Distro: Arch Linux x86_64 (kernel Version (Linux nickarch 4.0.1-1-ARCH #1 SMP PREEMPT Wed     Apr 29 12:00:26 CEST 2015 x86_64 GNU/Linux))
RAM: 16GB 1600 Mhz
CPU: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
GFX: 1GB Nvidia 650 Ti (Driver = Nvidia Version 349.16-2)
Enviroment: Openbox

If you would like any other information please let me know.

Nicholas C

**Comment by vpltd-peterm** [comment]
The game uses OpenAL Soft for it's audio, so it will load and use any .alsoftrc you have. Could it be that this is configured incorrectly?

Also, as it's Arch, you may find some odd library compatibility issue. The game comes with it's own libopenal-eon.so.1 in the installation folder - you may want to try symlinking this to Arch's native libopenal. As long as it is 1.16.0 or later, it should work.

**Comment by kartious** [comment]
Thanks for getting back to me. I do not appear to have a ./alsoftrc file in my home directory and just to clarify I have three native libraries which are

/lib/libopenal.so
/lib/libopenal.so.1
/lib/libopenal.so.1.16.0

You would like me to create a Symbolic Link from the libopenal-eon.so.1 in the Bioshock Infinite directory to /lib/libopenal.so.1.16.0 ?

Nicholas

**Comment by vpltd-peterm** [comment]
You will find the first two are symlinks to /lib/libopenal.so.1.16.0

Yes, try ln -s ./lib/libopenal.so.1.16.0 libopenal-eon.so.1, after having renamed the original shipping libopenal-eon.so.1

**Comment by vpltd-peterm** [comment]
Oh, just thought - you will need to be sure those are 32 bit builds of openal. If they are not, they will not work. I'm not familiar with how Arch handles multiarch libs to tell you where they should be.

**Comment by kartious** [comment]
After taking into account about the 32 bit builds of openal I have used the /usr/lib32/ libraries as this is where Arch handles 32 bit user session binaries. I have backed up the libopenal-eon.so.1 file in the Bioshock Infinite directory and then done a symbolic link from /usr/lib32 to the Bioshock Infinite directory which was for me:

ln -s /usr/lib32/libopenal.so.1.16.0 /home/nick/.local/share/Steam/SteamApps/common/BioShock\ Infinite/libopenal-eon.so.1

But the sound issue unfortunatly still persists. Have I done something wrong here?

**Comment by vpltd-peterm** [comment]
Try using openal-soft's logging to see what is going on
https://github.com/kcat/openal-soft/blob/master/env-vars.txt

**Comment by kartious** [comment]
I have given it a few days to try and do this but I am not familiar with it, could you please provide some guidance or a link to instructions on how to do this please?

**Comment by vpltd-peterm** [comment]
I'm afraid I'm unable to provide support for Arch as we do not use it in house. Ultimately though, this is a system specific problem, and not an issue with the game, so I am closing the bug
