### ISSUE TITLE
The game doesn't run from an XFS filesystem

### ISSUE THREAD

**Issue by vpltd-peterm** [virtual-programming/bioshockinfinite-linux#2]
As released, the game does not run from an xfs filesystem, or any filesystem where the d_type field is not supported by readdir().

We are aware of this and a fix will be in the next released version.

**Comment by kernelOfTruth** [comment]
related: https://github.com/ValveSoftware/Source-1-Games/issues/1685

**Comment by vpltd-peterm** [comment]
Actually it isnt.. we are 64 bit clean in this regard. It is to do with our filesystem code which handles case sensitive translation.

**Comment by kernelOfTruth** [comment]
I see, in the context: it works fine on ZFS (perchance I might be the only one running it on the aforementioned)

anyway: great work on the port :+1:

**Comment by vpltd-peterm** [comment]
This should now be fixed with build 604497

**Comment by vpltd-peterm** [comment]
Closing bug as I see from various posts on Steam that it is resolved
