### ISSUE TITLE
huge lag spikes after update

### ISSUE THREAD

**Issue by aramil248** [virtual-programming/bioshockinfinite-linux#22]
so when i saw that the game updated and isaw that the amd freeze issue was fixed i loaded up the game to test it out. but now it runs at like 30fps for a bit then all of a sudden its lagging really bad like 1-3fps. my pc specs http://pastebin.com/VvwvDqZ2

**Comment by christopherbeneke** [comment]
Hey try this.  I found it elsewhere and it seemed to fix the issue for me except when the steam achievements pop up.

Open the properties of the game in Steam. In the first tab you have a button "Set launch options". Put "-ReadTexturePoolFromIni" (without the quotes) as the launch option.  Then right-click on BioShock Infinite in your Steam Library, click Properties, select the Local Files tab, then click "Browse Local Files". In the directory that opens, navigate to XGame/Config and edit "DefaultEngine.ini"

In DefaultEngine.ini, find the line that says "PoolSize=400" and change it to a larger number. Try increasing by increments of 200 MB until you see an improvement in the stuttering, and stop if the problem gets worse.

I found that using PoolSize=2000 gives me much fewer lag spikes.

**Comment by aramil248** [comment]
thanks for the tip but its still lagging

**Comment by CommanderAlchemy** [comment]
@christopherbeneke if you read the comments in the file you will find out that it calculates that automaticly.

Tried to find anything other but it seems that the lagging is caused by eON wrapper itself. Though higher streaming of textures would be nice, atleast Wolfenstein had this in settings.

**Comment by aramil248** [comment]
A month later and I still can't play my game I got it working before last update but had to put stuff in terminal and launch options but I forgot what I used and would rather not do that

**Comment by vpltd-peterm** [comment]
If you are using an nvidia card, try deleting the ${HOME}/.nv/GLCache folder.

**Comment by aramil248** [comment]
It worked but its still lagging a bit but not like last time
