### ISSUE TITLE
Logitech F710 trigger buttons stopped working, probably after update

### ISSUE THREAD

**Issue by geochelone** [virtual-programming/bioshockinfinite-linux#23]
Hi Support Team,

a couple of days ago, the trigger buttons on my F710 controllers stopped working in Bioshock Infinite. They still work in other Steam games, though. Other controller functions work fine. But a shooter without the triggers is not as much fun. ;-)
If I recall correctly, this coincides with the most recent game update, but I can't be 100% sure.
Please let me know if you require more information.
Thanks!

Regards,

Soenke

Steam System Information below:
---------------------------------------------
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3400 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Debian GNU/Linux testing (stretch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.0.0-2-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 650/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 346.72
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0xfc6
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 62.99" x 35.43"  (72.24" diag)
                                            160.0cm x 90.0cm  (183.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Nvidia GPU 42 HDMI/DP
    
Memory:
    RAM:  7917 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  436371 Mb
    Largest Free Hard Disk Block:  306528 Mb
    
Installed software:
    
Recent Failure Reports:

**Comment by karmictoucan** [comment]
Can confirm. I have the same issue with logitech F310 gamepad and Xbox360 wireless gamepad after game update.

**Comment by jogrue** [comment]
Same here on an up-to-date Archlinux machine with Xbox360 wired gamepad, it stopped to work recently. Tried it with xpad and the steamos-patched xpad version.

When testing with evtest, there is some activity for pressing the trigger button (at least for pressing or releasing the trigger button, when it is held in a fully triggered position there is no action)

**Comment by eydee** [comment]
Same here, not a Logitech relate issue, mine is a Trust GXT39. (Used in xinput mode, so it appears as a 360 controller for the game.)

I've just started playing and wanted to find out how it works out with a controller. I thought it was me not being able to find out how to shoot... o_O

If you open the main menu and close it, sometimes it works for one shot, then it goes out again. Maybe it's just random though.

**Comment by dubigrasu** [comment]
I can confirm also that this is happening on SteamOS 1.0 (Alchemist beta) with an wired Xbox 360 gamepad on build 655022.

The Left and Right triggers can be used only once, or more exactly once pressed they remain in that state.
For example you can start a fresh game, take the pistol and fire. The pistol will consume the whole clip even if you pressed the trigger only briefly and from that moment on the trigger becomes unresponsive. The same with the Left trigger.

This is definitely something that happened in the recent updates although I can't be sure in which one.
It happens that I kept an older build (547118) and when I overwrite the "bioshock.i386" exec with the older one I regain the correct gamepad behavior back.

For those willing to test it (if Peter is OK with this) you can take it from here: 
<A HREF='http://www.uploadmb.com/dw.php?id=1437605229'>build_547118.tar.gz</A>
Don't forget to make it executable.

**Comment by pic1701d** [comment]
Same here on SteamOs beta after latest update with Xbox 360 wireless controller.
All buttons work fine except LT/RT.

**Comment by eydee** [comment]
I can confirm that the older build posted does indeed work, though it has terrible performance compared to the current one.

**Comment by dubigrasu** [comment]
@eydee 
That's curious, I'm getting better results with the old build.
Benchmark at high settings (avg, min, max fps),

Build 655022:
108.04, 40.55, 222.02, Welcome Center
136.20, 55.61, 266.52, Town Center
128.06, 41.80, 310.46, Raffle
186.66, 71.67, 263.50, Monument Island
129.51, 37.72, 310.46, Overall

Build 547118:
119.48, 39.08, 187.44, Welcome Center
141.80, 58.17, 221.29, Town Center
130.80, 40.75, 209.64, Raffle
189.63, 73.95, 287.03, Monument Island
137.59, 39.08, 287.03, Overall

**Comment by eydee** [comment]
"That's curious, I'm getting better results with the old build."

You must have intel/nvidia hardware. Latest builds contain crucial AMD fixes though, and I have AMD/AMD.

**Comment by dubigrasu** [comment]
Yes, you're right, Intel+Nvidia.

**Comment by rpdillon** [comment]
Just to add an additional data point, I'm seeing this on (k)ubuntu 15.04 with both an old-school Logitech Dual Action as well as a Logitech F310.  It's pretty game-breaking for me, since I can't use mouse+keyboard to game (RSI issues).  Any word on a fix?

**Comment by Mernst1** [comment]
I also can comfirm this issue, playing with the DS4 Controller and the Triggers doesn't work anymore since the last update. Trying now the old build exec that is posted above.
The problem seems to affect all controllers.

**Comment by fogzot** [comment]
Idem here with MS XBox 360 wifi controller. Would be nice to hear from developer. :/

**Comment by geochelone** [comment]
Hi everyone,

just to let you know, since I originally posted this issue here, I have also been in touch with Virtual Programming via their zendesk support system. We are working on a solution over there (which means I provide information, they are doing the actual work). Will post here as soon as something is found.

Regards,

Soenke

**Comment by wleoncio** [comment]
Same here. Ubuntu 14.04 LTS, Xbox 360 wired gamepad. Triggers don't work, all other buttons are fine. Both sticks, however, are behaving terribly, with erratic acceleration even after turning acceleration off on settings. Is anyone else experiencing this?

**Comment by wleoncio** [comment]
Here is a workaround:
Install Antimicro (Linux), or whatever it is you use to map mouse and keyboard buttons on gamepad on Windows and Mac. Then map LT and RT to the left and right mouse buttons.

As for the acceleration issue I was having, the solution was to unplug my mouse and keyboard during play. Apparently, this game has a problem with multiple input devices plugged in.

This has finally made those game playable for me, I hope it helps someone else!

**Comment by Dablim** [comment]
Same here with Ubuntu GNOME 15.04.

**Comment by Noki0100** [comment]
Same here (with my sisters PC) with Mint 17.1 Cinnamon on a 360 Controller.

**Comment by vpltd-peterm** [comment]
We may have found the cause of this in another title (Dirt Showdown). We are planning to release updates to affected titles.

**Comment by amoffat** [comment]
+1 Looking forward to the update

**Comment by finnschiermer** [comment]
+1 me too

**Comment by jay-to-the-dee** [comment]
Also have this issue using default 'xpad' kernel driver on wireless 360 controller, Ubuntu 15.04.

**Comment by vpltd-peterm** [comment]
We have a fix for this in testing at the moment.

**Comment by karmictoucan** [comment]
It seems that the issue was fixed in the latest update.

**Comment by geochelone** [comment]
Seems fixed for me after latest update, closing this issue.
Thanks for the support!

**Comment by amoffat** [comment]
Confirmed works as well.  You guys are great, thanks!

**Comment by jay-to-the-dee** [comment]
Can confirm, update completely fixes this! Thanks guys for being so quick about this! XD

**Comment by finnschiermer** [comment]
Fix confirmed. Thanks.
