### ISSUE TITLE
Official microsoft Xbox 360 wireless controller

### ISSUE THREAD

**Issue by Gabullito** [virtual-programming/bioshockinfinite-linux#26]
Hello,
I have an issue with my gamepad buttons ( LT RT LB RB ) not working in game
Cordialy
OS: SteamOS 1.0
Gamepad : Official microsoft Xbox 360 wireless controller

**Comment by dubigrasu** [comment]
Most likely the same issue as https://github.com/virtual-programming/bioshockinfinite-linux/issues/23

**Comment by vpltd-peterm** [comment]
Closing as duplicate of #23
