### ISSUE TITLE
System requirements should now be adjusted

### ISSUE THREAD

**Issue by eydee** [virtual-programming/bioshockinfinite-linux#28]
Now that fglrx has been fixed and the game runs fine on Terascale GPUs too (HD 5k and 6k), maybe the official system requirements should be adjusted. (After internal testing, if needed.) Let more people enjoy this great work!

**Comment by vpltd-peterm** [comment]
We've advised 2K of the revised system specs... but they control what is listed on the Steam store page. We will remind them :)

**Comment by vpltd-peterm** [comment]
Closing as this isn't a bug...
