### ISSUE TITLE
E.runloop becomes a zombie after shutdown.

### ISSUE THREAD

**Issue by CallakSkytower** [virtual-programming/bioshockinfinite-linux#30]
The game starts and runs fine, but every time I exit the game, it seems to close properly, but E.runloop becomes a zombie process. If I try to start the game again, steam thinks it's already running until I manually kill E.runloop.

Operating System Version:
Ubuntu 14.04.2 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 3.13.0-61-generic
X Server Vendor: The X.Org Foundation
X Server Release: 11501000
X Window Manager: KWin

**Comment by CallakSkytower** [comment]
Additional data:
Console output after a short run and close:
Installing breakpad exception handler for appid(bioshock)/version(1.0)
ERROR: ld.so: object '/home/callak/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20150810063525_8.dmp[8423]: Uploading dump (out-of-process)
/tmp/dumps/crash_20150810063525_8.dmp
crash_20150810063525_8.dmp[8423]: Finished uploading minidump (out-of-process): success = yes
crash_20150810063525_8.dmp[8423]: response: Discarded=1
crash_20150810063525_8.dmp[8423]: file ''/tmp/dumps/crash_20150810063525_8.dmp'', upload yes: ''Discarded=1''
pid 8423 != 8421, skipping destruction (fork without exec?)
Bad thread localBad thread localBad thread local

Eon.txt:
https://www.dropbox.com/s/iihekr9cl7jrbco/eon.txt?dl=0

**Comment by vpltd-peterm** [comment]
That crash dump is made by the Steam overlay, which then causes the process to hang. We saw this during development and reported it to Valve. They reported it as fixed, and we never saw the issue after that.

I can only suggest reporting this problem to Valve.

**Comment by vpltd-peterm** [comment]
Closing as it's an issue with Steam overlay, not the game itself
