### ISSUE TITLE
Xbox One controller trigger buttons dont work

### ISSUE THREAD

**Issue by creeperlwd** [virtual-programming/bioshockinfinite-linux#33]
Arch linux 4.1.6-1
Official xbox one controller
I tried other gamepad profiles that also didnt work

**Comment by vpltd-peterm** [comment]
We may have found the cause of this in another title (Dirt Showdown). We are planning to release updates to affected titles.

**Comment by vpltd-peterm** [comment]
Closing as duplicate of #23
