### ISSUE TITLE
Bioshock Infinite "Disk Write Error"

### ISSUE THREAD

**Issue by mwf12692** [virtual-programming/bioshockinfinite-linux#34]
Every time I try to download the game it completes the download and gives me a disk write error. I'm sure that the hard drive is not the issue as I have over a TB of memory and the CPU is brand new. I've been trying to resolve this issue for over two weeks and I keep getting bounced around from 2K support to Feral to Aspyr and finally to this site. Thanks in advance for your help and let me know if you need anymore information from me.

**Comment by vpltd-peterm** [comment]
"Disk Write Error" is an issue with Steam, not the game itself. Please contact Steam support.
