### ISSUE TITLE
let bioshock infinite run even without pulseaudio

### ISSUE THREAD

**Issue by karolherbst** [virtual-programming/bioshockinfinite-linux#37]
Would that be possible? Or is pulse required as a hard requiernement?

**Comment by vpltd-peterm** [comment]
Bioshock Infinite uses openal-soft for it's audio - you may configure this to use alsa using .alsoftrc configuration file. See here for details:

http://repo.or.cz/w/openal-soft.git/blob/HEAD:/alsoftrc.sample

**Comment by karolherbst** [comment]
ohh thanks, that works indeed. The issue is, that steam needs pulseaudio, but there is "apulse" to fake pulseaudio support. Sadly the steamclient.so library also needs pulse, otherwise it can't be load and bioshock won't start because of that.

And because I ran also bioshock through apulse it defaulted to pulseaudio not alsa, so I just thought bioshock also needs pulseaudio :)
