### ISSUE TITLE
Projectors missing narrators voice (german version)

### ISSUE THREAD

**Issue by vincent-t** [virtual-programming/bioshockinfinite-linux#5]
When using the projectors the narrators voice is missing.
Systeminformation:
OS: Manjaro 0.8.12 Ascella
Kernel: x86_64 Linux 4.0.0-1-MANJARO
Shell: bash 4.3.33
Resolution: 1920x1080
DE: XFCE4
WM: Xfwm4
CPU: Intel Core i5-2300 CPU @ 2.8GHz
GPU: GeForce GTX 660
RAM: 16020MB

**Comment by vpltd-peterm** [comment]
Is this when using the Kinetoscopes ? If so, they are meant to be silent

**Comment by vincent-t** [comment]
Yes, i thought they had voice when i played bioshock infinite the last time on windows but i was wrong. Sorry.
