### ISSUE TITLE
Pixelated artifacts on some textures

### ISSUE THREAD

**Issue by Fastolph** [virtual-programming/bioshockinfinite-linux#8]
Some textures representing marble during the first part of the Burial At Sea DLC have pixelated artifacts that doesn't seems intended. Here's some pictures:

![8870_2015-03-18_00004](https://cloud.githubusercontent.com/assets/974506/7321057/4f3e6ec4-eaa0-11e4-8189-ed6352510dd5.png)
![8870_2015-03-18_00012](https://cloud.githubusercontent.com/assets/974506/7321066/5e0e502c-eaa0-11e4-9e42-7b586e5fa23e.png)
![8870_2015-03-18_00013](https://cloud.githubusercontent.com/assets/974506/7321067/5e46d3ca-eaa0-11e4-9584-87f3eb6bb7f1.png)

They appear both with or without antialiasing. Easiest way to reach them is loading the "Marketplace" chapter and going to "The Golden Rule" jewelry shop.

I'm running a 64bits ArchLinux with proprietary Nvidia drivers (346.59) and KWin as a window manager and compositor. As for hardware it's an Intel i7-4790K CPU and an MSI GTX 980 (4GB VRAM).

**Comment by vpltd-peterm** [comment]
Make sure you have "Texture Sharpening" disabled in the nVidia control panel

**Comment by Fastolph** [comment]
Sorry for the late reply. That indeed fixed the issue, thanks. Now I'm curious about that exacly Texture Sharpening does.
